
//Insertamos los generos
db.generos.insertMany([
    {"_id":1,"genero":"Gore","popularidad":88},
    {"_id":2,"genero":"Mystery","popularidad":40},
    {"_id":3,"genero":"Drama","popularidad":57},
    {"_id":4,"genero":"Documentary","popularidad":43},
    {"_id":5,"genero":"Romance","popularidad":84},
    {"_id":6,"genero":"Thriller","popularidad":6},
    {"_id":7,"genero":"Adventure","popularidad":42},
    {"_id":8,"genero":"Crime","popularidad":6},
    {"_id":9,"genero":"Comedy","popularidad":39},
    {"_id":10,"genero":"Fantasy","popularidad":91}])


//Insertamos las peliculas
db.peliculas.insertMany([
    {"_id":1,"genero":7,"titulo":"L'homme qui rit","protagonista":"Tuck"},
    {"_id":2,"genero":4,"titulo":"Before the Fall (NaPolA - Elite für den Führer)","protagonista":"Skylar"},
    {"_id":3,"genero":6,"titulo":"Talk Radio","protagonista":"Gerard"},
    {"_id":4,"genero":4,"titulo":"Secuestro Express","protagonista":"Ardys"},
    {"_id":5,"genero":4,"titulo":"Her Highness and the Bellboy","protagonista":"Georgie"},
    {"_id":6,"genero":5,"titulo":"Day the Earth Stood Still, The","protagonista":"Abigail"},
    {"_id":7,"genero":5,"titulo":"My Mother Likes Women (A mi madre le gustan las mujeres)","protagonista":"Jordan"},
    {"_id":8,"genero":1,"titulo":"Jewel of the Nile, The","protagonista":"Torey"},
    {"_id":9,"genero":1,"titulo":"Eve's Bayou","protagonista":"Hans"},
    {"_id":10,"genero":5,"titulo":"Youth of the Beast (Yaju no seishun)","protagonista":"Enoch"},
    {"_id":11,"genero":3,"titulo":"Alone in the Dark","protagonista":"Tracey"},
    {"_id":12,"genero":2,"titulo":"Willow Creek","protagonista":"Emelina"},
    {"_id":13,"genero":8,"titulo":"Revolution OS","protagonista":"Kylie"},
    {"_id":14,"genero":4,"titulo":"Talhotblond:","protagonista":"Clo"},
    {"_id":15,"genero":2,"titulo":"Devil and Daniel Johnston, The","protagonista":"Clint"},
    {"_id":16,"genero":4,"titulo":"Brief Interviews with Hideous Men","protagonista":"Granny"},
    {"_id":17,"genero":7,"titulo":"Reel Rock 8 ","protagonista":"Adrianna"},
    {"_id":18,"genero":1,"titulo":"I Do: How to Get Married and Stay Single (Prête-moi ta main)","protagonista":"Dorette"},
    {"_id":19,"genero":9,"titulo":"Donkey Hide (Oslinaya shkura)","protagonista":"Fifine"},
    {"_id":20,"genero":4,"titulo":"Night of the Shooting Stars (Notte di San Lorenzo, La)","protagonista":"Tedie"},
    {"_id":21,"genero":1,"titulo":"Lucky","protagonista":"Hermon"},
    {"_id":22,"genero":3,"titulo":"Beautiful Country, The","protagonista":"Happy"},
    {"_id":23,"genero":8,"titulo":"Full House (O. Henry's Full House)","protagonista":"Anny"},
    {"_id":24,"genero":4,"titulo":"Hedwig and the Angry Inch","protagonista":"Saree"},
    {"_id":25,"genero":7,"titulo":"Species II","protagonista":"Parrnell"},
    {"_id":26,"genero":3,"titulo":"Zizek!","protagonista":"Rich"},
    {"_id":27,"genero":9,"titulo":"Studentfesten","protagonista":"Archambault"},
    {"_id":28,"genero":1,"titulo":"Sanctum","protagonista":"Harman"},
    {"_id":29,"genero":1,"titulo":"Cabinet of Dr. Caligari, The (Cabinet des Dr. Caligari., Das)","protagonista":"Esta"},
    {"_id":30,"genero":2,"titulo":"Ali G Indahouse","protagonista":"Georgine"},
    {"_id":31,"genero":1,"titulo":"Under the Skin","protagonista":"Zena"},
    {"_id":32,"genero":3,"titulo":"Dara Ó Briain Talks Funny: Live in London","protagonista":"Rozanne"},
    {"_id":33,"genero":6,"titulo":"Paradise, Hawaiian Style","protagonista":"Cynde"},
    {"_id":34,"genero":10,"titulo":"Abraham's Valley (Vale Abraão)","protagonista":"Alberto"},
    {"_id":35,"genero":10,"titulo":"Crystal Lake Memories: The Complete History of Friday the 13th","protagonista":"Yul"},
    {"_id":36,"genero":1,"titulo":"Dark Tide","protagonista":"Gabriellia"},
    {"_id":37,"genero":1,"titulo":"Quadrille","protagonista":"Karlyn"},
    {"_id":38,"genero":1,"titulo":"Addams Family Values","protagonista":"Lazarus"},
    {"_id":39,"genero":2,"titulo":"About Last Night","protagonista":"Hildagard"},
    {"_id":40,"genero":3,"titulo":"Beck - Familjen","protagonista":"Deni"},
    {"_id":41,"genero":7,"titulo":"Ashik Kerib","protagonista":"Philbert"},
    {"_id":42,"genero":7,"titulo":"Goodbye, Mr. Chips","protagonista":"Thaddus"},
    {"_id":43,"genero":6,"titulo":"Strangers in Good Company","protagonista":"Orin"},
    {"_id":44,"genero":3,"titulo":"Tupac: Resurrection","protagonista":"Lory"},
    {"_id":45,"genero":7,"titulo":"Thin Ice","protagonista":"Pail"},
    {"_id":46,"genero":8,"titulo":"Abendland","protagonista":"Pebrook"},
    {"_id":47,"genero":7,"titulo":"Tormento","protagonista":"Rania"},
    {"_id":48,"genero":3,"titulo":"Once Around","protagonista":"Kimball"},
    {"_id":49,"genero":9,"titulo":"Sexual Life of the Belgians, The (Vie sexuelle des Belges 1950-1978, La)","protagonista":"Alissa"},
    {"_id":50,"genero":4,"titulo":"Twister","protagonista":"Idaline"},
    {"_id":51,"genero":7,"titulo":"Saturday Night Fever","protagonista":"Goldina"},
    {"_id":52,"genero":7,"titulo":"The Deep Six","protagonista":"Benjamin"},
    {"_id":53,"genero":10,"titulo":"Freedomfighters (Libertarias)","protagonista":"Shelia"},
    {"_id":54,"genero":1,"titulo":"Across 110th Street","protagonista":"Lissa"},
    {"_id":55,"genero":8,"titulo":"Life Less Ordinary, A","protagonista":"Ulric"},
    {"_id":56,"genero":7,"titulo":"Chicken Run","protagonista":"Ellissa"},
    {"_id":57,"genero":2,"titulo":"Generale Della Rovere, Il","protagonista":"Lilias"},
    {"_id":58,"genero":8,"titulo":"Dementia (a.k.a. Daughter of Horror)","protagonista":"Trista"},
    {"_id":59,"genero":9,"titulo":"3rd World Hero (Bayaning Third World)","protagonista":"Edd"},
    {"_id":60,"genero":6,"titulo":"Backbeat","protagonista":"Corly"},
    {"_id":61,"genero":9,"titulo":"Fathom","protagonista":"Masha"},
    {"_id":62,"genero":4,"titulo":"God of Cookery (Sik san)","protagonista":"Gayle"},
    {"_id":63,"genero":9,"titulo":"Women Art Revolution","protagonista":"Poppy"},
    {"_id":64,"genero":7,"titulo":"God on Trial","protagonista":"Bibbie"},
    {"_id":65,"genero":9,"titulo":"Witness","protagonista":"Nicolina"},
    {"_id":66,"genero":5,"titulo":"Communion","protagonista":"Todd"},
    {"_id":67,"genero":6,"titulo":"James Gandolfini: Tribute to a Friend","protagonista":"Clerissa"},
    {"_id":68,"genero":3,"titulo":"They Were Expendable","protagonista":"Porter"},
    {"_id":69,"genero":3,"titulo":"Hot Fuzz","protagonista":"Sigmund"},
    {"_id":70,"genero":8,"titulo":"Comrade X","protagonista":"Cesare"},
    {"_id":71,"genero":9,"titulo":"Escape","protagonista":"Zechariah"},
    {"_id":72,"genero":10,"titulo":"Tyler Perry's Daddy's Little Girls","protagonista":"Westbrooke"},
    {"_id":73,"genero":7,"titulo":"Whatever It Takes","protagonista":"Casey"},
    {"_id":74,"genero":7,"titulo":"I Love You, I Love You (Je t'aime je t'aime)","protagonista":"Crissie"},
    {"_id":75,"genero":5,"titulo":"Marilyn Hotchkiss' Ballroom Dancing & Charm School","protagonista":"Hilario"},
    {"_id":76,"genero":1,"titulo":"Children of the Living Dead","protagonista":"Chiquita"},
    {"_id":77,"genero":3,"titulo":"Compliance","protagonista":"Phaedra"},
    {"_id":78,"genero":10,"titulo":"Rugrats Movie, The","protagonista":"Andree"},
    {"_id":79,"genero":9,"titulo":"Haunted Mansion, The","protagonista":"Thomas"},
    {"_id":80,"genero":6,"titulo":"Eyes of Tammy Faye, The","protagonista":"Douglass"},
    {"_id":81,"genero":6,"titulo":"Shout, The","protagonista":"Domenic"},
    {"_id":82,"genero":3,"titulo":"Lush Life","protagonista":"Gussi"},
    {"_id":83,"genero":3,"titulo":"2012: Supernova","protagonista":"Fax"},
    {"_id":84,"genero":10,"titulo":"House That Dripped Blood, The","protagonista":"Cliff"},
    {"_id":85,"genero":8,"titulo":"Time Stood Still (Il tempo si è fermato)","protagonista":"Mela"},
    {"_id":86,"genero":8,"titulo":"Roger Dodger","protagonista":"Nancy"},
    {"_id":87,"genero":6,"titulo":"Salon Kitty","protagonista":"Rowena"},
    {"_id":88,"genero":9,"titulo":"Dangerous Man, A","protagonista":"Rudolph"},
    {"_id":89,"genero":6,"titulo":"Mysterious X, The (Sealed Orders) (Det hemmelighedsfulde X)","protagonista":"Krystle"},
    {"_id":90,"genero":6,"titulo":"Mind Reader, The","protagonista":"Maire"},
    {"_id":91,"genero":5,"titulo":"Somewhere in the City","protagonista":"Lishe"},
    {"_id":92,"genero":8,"titulo":"Swingers","protagonista":"Sigvard"},
    {"_id":93,"genero":10,"titulo":"Nicholas on Holiday","protagonista":"Lynne"},
    {"_id":94,"genero":5,"titulo":"Private Property (Nue propriété)","protagonista":"Dulci"},
    {"_id":95,"genero":2,"titulo":"Mount St. Elias","protagonista":"Sibby"},
    {"_id":96,"genero":6,"titulo":"Tender Is the Night","protagonista":"Clyde"},
    {"_id":97,"genero":1,"titulo":"Other F Word, The","protagonista":"Brooke"},
    {"_id":98,"genero":8,"titulo":"Contact High","protagonista":"Celene"},
    {"_id":99,"genero":6,"titulo":"Marley","protagonista":"Xylia"},
    {"_id":100,"genero":4,"titulo":"All In This Tea","protagonista":"Emmalyn"}])