//Inserciones de estudiantes
db.estudiantes.insertMany([
    {_id:1,nombre:"Raine",apellidos:"Knoles",email:"rknoles0@multiply.com",genero:"F",carrera:7},
    {_id:2,nombre:"Mahalia",apellidos:"McMurty",email:"mmcmurty1@gmpg.org",genero:"F",carrera:8},
    {_id:3,nombre:"Keven",apellidos:"Algy",email:"kalgy2@utexas.edu",genero:"M",carrera:4},
    {_id:4,nombre:"Fay",apellidos:"Jobin",email:"fjobin3@telegraph.co.uk",genero:"F",carrera:6},
    {_id:5,nombre:"Tarra",apellidos:"Streetley",email:"tstreetley4@craigslist.org",genero:"F",carrera:6},
    {_id:6,nombre:"Car",apellidos:"Merrikin",email:"cmerrikin5@cmu.edu",genero:"M",carrera:9},
    {_id:7,nombre:"Charleen",apellidos:"Burke",email:"cburke6@webs.com",genero:"F",carrera:10},
    {_id:8,nombre:"Gino",apellidos:"Extall",email:"gextall7@hatena.ne.jp",genero:"M",carrera:9},
    {_id:9,nombre:"Yetta",apellidos:"Andrejs",email:"yandrejs8@ted.com",genero:"F",carrera:3},
    {_id:10,nombre:"Jamil",apellidos:"Mattedi",email:"jmattedi9@nyu.edu",genero:"M",carrera:10},
    {_id:11,nombre:"Michelle",apellidos:"Callard",email:"mcallarda@taobao.com",genero:"F",carrera:2},
    {_id:12,nombre:"Micky",apellidos:"Burdoun",email:"mburdounb@nytimes.com",genero:"M",carrera:1},
    {_id:13,nombre:"Janos",apellidos:"Worden",email:"jwordenc@moonfruit.com",genero:"M",carrera:9},
    {_id:14,nombre:"Gonzalo",apellidos:"Buggs",email:"gbuggsd@twitter.com",genero:"M",carrera:7},
    {_id:15,nombre:"Abba",apellidos:"Ambrosetti",email:"aambrosettie@engadget.com",genero:"M",carrera:6},
    {_id:16,nombre:"Stacy",apellidos:"Temporal",email:"stemporalf@si.edu",genero:"F",carrera:2},
    {_id:17,nombre:"Egbert",apellidos:"Thredder",email:"ethredderg@deviantart.com",genero:"M",carrera:1},
    {_id:18,nombre:"Jonathon",apellidos:"Raymen",email:"jraymenh@lulu.com",genero:"M",carrera:10},
    {_id:19,nombre:"Elizabeth",apellidos:"Rubinowicz",email:"erubinowiczi@eventbrite.com",genero:"F",carrera:6},
    {_id:20,nombre:"Dannie",apellidos:"Buyers",email:"dbuyersj@reverbnation.com",genero:"F",carrera:4},
    {_id:21,nombre:"Kimberlee",apellidos:"Deans",email:"kdeansk@prlog.org",genero:"F",carrera:4},
    {_id:22,nombre:"Ralf",apellidos:"Thomasen",email:"rthomasenl@ihg.com",genero:"M",carrera:4},
    {_id:23,nombre:"Collin",apellidos:"Keady",email:"ckeadym@rediff.com",genero:"M",carrera:3},
    {_id:24,nombre:"John",apellidos:"Halfhide",email:"jhalfhiden@t.co",genero:"M",carrera:8},
    {_id:25,nombre:"Emmanuel",apellidos:"Pampling",email:"epamplingo@sitemeter.com",genero:"M",carrera:3},
    {_id:26,nombre:"Kerry",apellidos:"Rowena",email:"krowenap@dailymail.co.uk",genero:"M",carrera:6},
    {_id:27,nombre:"Jasen",apellidos:"Kennelly",email:"jkennellyq@un.org",genero:"M",carrera:7},
    {_id:28,nombre:"Madella",apellidos:"Cawood",email:"mcawoodr@usda.gov",genero:"F",carrera:10},
    {_id:29,nombre:"Gale",apellidos:"Doget",email:"gdogets@dyndns.org",genero:"F",carrera:10},
    {_id:30,nombre:"Melody",apellidos:"Radenhurst",email:"mradenhurstt@indiegogo.com",genero:"F",carrera:10},
    {_id:31,nombre:"Ram",apellidos:"Duesberry",email:"rduesberryu@nps.gov",genero:"M",carrera:3},
    {_id:32,nombre:"Berkly",apellidos:"Barnson",email:"bbarnsonv@phpbb.com",genero:"M",carrera:10},
    {_id:33,nombre:"Ambrose",apellidos:"Leads",email:"aleadsw@weibo.com",genero:"M",carrera:2},
    {_id:34,nombre:"Addy",apellidos:"Lygo",email:"alygox@altervista.org",genero:"F",carrera:2},
    {_id:35,nombre:"Cybill",apellidos:"Puckring",email:"cpuckringy@shop-pro.jp",genero:"F",carrera:9},
    {_id:36,nombre:"Turner",apellidos:"Barnes",email:"tbarnesz@blinklist.com",genero:"M",carrera:7},
    {_id:37,nombre:"Karmen",apellidos:"Zannelli",email:"kzannelli10@yellowbook.com",genero:"F",carrera:2},
    {_id:38,nombre:"Delores",apellidos:"Laterza",email:"dlaterza11@wikimedia.org",genero:"F",carrera:7},
    {_id:39,nombre:"Roby",apellidos:"Poutress",email:"rpoutress12@instagram.com",genero:"F",carrera:9},
    {_id:40,nombre:"Jodie",apellidos:"Weymouth",email:"jweymouth13@addthis.com",genero:"F",carrera:2},
    {_id:41,nombre:"Margy",apellidos:"Niblock",email:"mniblock14@issuu.com",genero:"F",carrera:8},
    {_id:42,nombre:"Vance",apellidos:"Gilleson",email:"vgilleson15@go.com",genero:"M",carrera:4},
    {_id:43,nombre:"Wendye",apellidos:"Sadry",email:"wsadry16@nationalgeographic.com",genero:"F",carrera:1},
    {_id:44,nombre:"Damaris",apellidos:"Stapylton",email:"dstapylton17@icio.us",genero:"F",carrera:4},
    {_id:45,nombre:"De witt",apellidos:"Jenckes",email:"djenckes18@constantcontact.com",genero:"M",carrera:7},
    {_id:46,nombre:"Asia",apellidos:"Ors",email:"aors19@soundcloud.com",genero:"F",carrera:7},
    {_id:47,nombre:"Dalt",apellidos:"Semble",email:"dsemble1a@redcross.org",genero:"M",carrera:8},
    {_id:48,nombre:"Rafaela",apellidos:"Decreuze",email:"rdecreuze1b@prlog.org",genero:"F",carrera:10},
    {_id:49,nombre:"Curtice",apellidos:"Copcott",email:"ccopcott1c@apple.com",genero:"M",carrera:1},
    {_id:50,nombre:"Dallon",apellidos:"Thoday",email:"dthoday1d@reference.com",genero:"M",carrera:7},
    {_id:51,nombre:"Griffy",apellidos:"Ousley",email:"gousley1e@ibm.com",genero:"M",carrera:3},
    {_id:52,nombre:"Natalie",apellidos:"Fuzzey",email:"nfuzzey1f@gizmodo.com",genero:"F",carrera:3},
    {_id:53,nombre:"Grace",apellidos:"Croce",email:"gcroce1g@t-online.de",genero:"F",carrera:2},
    {_id:54,nombre:"Ginevra",apellidos:"Habbon",email:"ghabbon1h@wordpress.org",genero:"F",carrera:2},
    {_id:55,nombre:"Domini",apellidos:"Hinz",email:"dhinz1i@foxnews.com",genero:"F",carrera:6},
    {_id:56,nombre:"Joana",apellidos:"Hyne",email:"jhyne1j@seesaa.net",genero:"F",carrera:6},
    {_id:57,nombre:"Marni",apellidos:"Scourfield",email:"mscourfield1k@wisc.edu",genero:"F",carrera:1},
    {_id:58,nombre:"Godiva",apellidos:"Airy",email:"gairy1l@topsy.com",genero:"F",carrera:10},
    {_id:59,nombre:"Jacinta",apellidos:"Knellen",email:"jknellen1m@vistaprint.com",genero:"F",carrera:2},
    {_id:60,nombre:"Gun",apellidos:"Steabler",email:"gsteabler1n@nymag.com",genero:"M",carrera:3},
    {_id:61,nombre:"Karita",apellidos:"Chazelas",email:"kchazelas1o@constantcontact.com",genero:"F",carrera:5},
    {_id:62,nombre:"Kaitlynn",apellidos:"Gogarty",email:"kgogarty1p@mozilla.com",genero:"F",carrera:6},
    {_id:63,nombre:"Cecilius",apellidos:"Hackney",email:"chackney1q@discuz.net",genero:"M",carrera:1},
    {_id:64,nombre:"Niels",apellidos:"Bucknall",email:"nbucknall1r@slate.com",genero:"M",carrera:7},
    {_id:65,nombre:"Daryl",apellidos:"Hunstone",email:"dhunstone1s@ucoz.com",genero:"F",carrera:2},
    {_id:66,nombre:"Sydel",apellidos:"Cattlow",email:"scattlow1t@domainmarket.com",genero:"F",carrera:2},
    {_id:67,nombre:"Lynett",apellidos:"Laughtisse",email:"llaughtisse1u@wp.com",genero:"F",carrera:10},
    {_id:68,nombre:"Geordie",apellidos:"Showt",email:"gshowt1v@issuu.com",genero:"M",carrera:5},
    {_id:69,nombre:"Aliza",apellidos:"Yendle",email:"ayendle1w@surveymonkey.com",genero:"F",carrera:9},
    {_id:70,nombre:"Raymund",apellidos:"Coat",email:"rcoat1x@csmonitor.com",genero:"M",carrera:9},
    {_id:71,nombre:"Harli",apellidos:"Antley",email:"hantley1y@lulu.com",genero:"F",carrera:2},
    {_id:72,nombre:"Debera",apellidos:"Fahrenbacher",email:"dfahrenbacher1z@ameblo.jp",genero:"F",carrera:5},
    {_id:73,nombre:"Nettie",apellidos:"Osselton",email:"nosselton20@cbsnews.com",genero:"F",carrera:9},
    {_id:74,nombre:"Annaliese",apellidos:"Stubbert",email:"astubbert21@nytimes.com",genero:"F",carrera:7},
    {_id:75,nombre:"Pepita",apellidos:"Cassey",email:"pcassey22@umich.edu",genero:"F",carrera:10},
    {_id:76,nombre:"Kacey",apellidos:"Beckford",email:"kbeckford23@cloudflare.com",genero:"F",carrera:8},
    {_id:77,nombre:"Town",apellidos:"Hedling",email:"thedling24@economist.com",genero:"M",carrera:6},
    {_id:78,nombre:"Guillaume",apellidos:"Stickland",email:"gstickland25@usda.gov",genero:"M",carrera:8},
    {_id:79,nombre:"Shepperd",apellidos:"Crain",email:"scrain26@aboutads.info",genero:"M",carrera:2},
    {_id:80,nombre:"Lawrence",apellidos:"Kildahl",email:"lkildahl27@bandcamp.com",genero:"M",carrera:6},
    {_id:81,nombre:"Hedy",apellidos:"Olifaunt",email:"holifaunt28@prnewswire.com",genero:"F",carrera:5},
    {_id:82,nombre:"Hercule",apellidos:"O'Gormley",email:"hogormley29@hp.com",genero:"M",carrera:8},
    {_id:83,nombre:"Ertha",apellidos:"Braisby",email:"ebraisby2a@godaddy.com",genero:"F",carrera:6},
    {_id:84,nombre:"Jesus",apellidos:"Schimann",email:"jschimann2b@latimes.com",genero:"M",carrera:8},
    {_id:85,nombre:"Tristan",apellidos:"Bakey",email:"tbakey2c@slideshare.net",genero:"M",carrera:4},
    {_id:86,nombre:"Davidde",apellidos:"Ridewood",email:"dridewood2d@unblog.fr",genero:"M",carrera:10},
    {_id:87,nombre:"Mahmud",apellidos:"Harrod",email:"mharrod2e@blogtalkradio.com",genero:"M",carrera:3},
    {_id:88,nombre:"Byron",apellidos:"M'cowis",email:"bmcowis2f@51.la",genero:"M",carrera:6},
    {_id:89,nombre:"Tailor",apellidos:"Van der Son",email:"tvanderson2g@goo.gl",genero:"M",carrera:2},
    {_id:90,nombre:"Jamie",apellidos:"Waterhous",email:"jwaterhous2h@free.fr",genero:"F",carrera:4},
    {_id:91,nombre:"Crosby",apellidos:"Kundert",email:"ckundert2i@github.com",genero:"M",carrera:10},
    {_id:92,nombre:"Viviyan",apellidos:"Renzini",email:"vrenzini2j@google.co.jp",genero:"F",carrera:4},
    {_id:93,nombre:"Algernon",apellidos:"Donavan",email:"adonavan2k@simplemachines.org",genero:"M",carrera:4},
    {_id:94,nombre:"Eberhard",apellidos:"Karpman",email:"ekarpman2l@1688.com",genero:"M",carrera:5},
    {_id:95,nombre:"Valencia",apellidos:"Grainge",email:"vgrainge2m@macromedia.com",genero:"F",carrera:5},
    {_id:96,nombre:"Eveleen",apellidos:"Arnason",email:"earnason2n@businessweek.com",genero:"F",carrera:1},
    {_id:97,nombre:"Kelwin",apellidos:"Geffe",email:"kgeffe2o@ovh.net",genero:"M",carrera:8},
    {_id:98,nombre:"Manolo",apellidos:"Thackwray",email:"mthackwray2p@seattletimes.com",genero:"M",carrera:8},
    {_id:99,nombre:"Fawnia",apellidos:"Cullerne",email:"fcullerne2q@cam.ac.uk",genero:"F",carrera:3},
    {_id:100,nombre:"Rockey",apellidos:"Jansik",email:"rjansik2r@wikispaces.com",genero:"M",carrera:10}
    ])

//Ahora las universidades

db.universidades.insertMany([
    {"_id":1,"nombreCarrera":"Geologist IV","horas":669,"edificio":1},
    {"_id":2,"nombreCarrera":"Executive Secretary","horas":667,"edificio":2},
    {"_id":3,"nombreCarrera":"Occupational Therapist","horas":806,"edificio":3},
    {"_id":4,"nombreCarrera":"Automation Specialist I","horas":752,"edificio":4},
    {"_id":5,"nombreCarrera":"Quality Engineer","horas":737,"edificio":5},
    {"_id":6,"nombreCarrera":"Desktop Support Technician","horas":563,"edificio":6},
    {"_id":7,"nombreCarrera":"GIS Technical Architect","horas":569,"edificio":7},
    {"_id":8,"nombreCarrera":"Desktop Support Technician","horas":764,"edificio":8},
    {"_id":9,"nombreCarrera":"Technical Writer","horas":595,"edificio":9},
    {"_id":10,"nombreCarrera":"Professor","horas":583,"edificio":10}])